### ISSUE TITLE
void-function doom-modeline--set-char-widths

### ISSUE THREAD

**Issue by terryzhouke** [nasyxx/emacs.d#10]
doom-modeline remove “doom-modeline--set-char-widths” function

[Remove unnecessary workaround: doom-modeline-set-char-widths.](https://github.com/seagle0128/doom-modeline/commit/e138abb37679a86d48d3e05d3a8528bc391e8ba0)

**Comment by nasyxx** [comment]
Hi, 

I removed it https://github.com/nasyxx/emacs.d/commit/99634024b72a8ba3f8df1e8813acfe1fdd4a82fb.  

Should work now.
