### ISSUE TITLE
void-variable treesit-extra-load-path

### ISSUE THREAD

**Issue by terryzhouke** [nasyxx/emacs.d#11]
Debugger entered--Lisp error: (void-variable treesit-extra-load-path)
  (member x treesit-extra-load-path)
  (if (member x treesit-extra-load-path) treesit-extra-load-path (setq treesit-extra-load-path (cons x treesit-extra-load-path)))
  (let* ((x (concat *nasy-var* "treesit"))) (if (member x treesit-extra-load-path) treesit-extra-load-path (setq treesit-extra-load-path (cons x treesit-extra-load-path))))
  (closure (t) nil (let* ((x (concat *nasy-var* "treesit"))) (if (member x treesit-extra-load-path) treesit-extra-load-path (setq treesit-extra-load-path (cons x treesit-extra-load-path)))))()
  eval-after-load-helper("/opt/homebrew/Cellar/emacs-plus@29/29.0.60/share/emacs/29.0.60/lisp/treesit.elc")
  do-after-load-evaluation("/opt/homebrew/Cellar/emacs-plus@29/29.0.60/share/e...")
  require(treesit)

**Comment by nasyxx** [comment]
Hi, sorry for responding late.

The variable `treesit-extra-load-path` should exist in both emacs29 and emacs30.

See

https://github.com/emacs-mirror/emacs/blob/d879847cd4daaeef792384475dd31a3dcfc14184/src/treesit.c#L3587-L3595

**Comment by terryzhouke** [comment]
奇怪，我明明安装了 emacs 29。为什么老是提示这个错误
brew install emacs-plus@29 --with-dragon-icon --with-native-comp --with-imagemagick --with-poll

❯ emacs --version
GNU Emacs 29.0.90
Copyright (C) 2023 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
