### ISSUE TITLE
misusage of function

### ISSUE THREAD

**Issue by shynur** [nasyxx/emacs.d#12]
你好多 `*-hook` 前都加了 `#'`, 真的没问题吗?
`#'` 的语义是针对函数的吧?

另外看一下 `lambda` 宏的定义, `(lambda ...)` 展开之后就是 `#'(lambda ...)`, 所以 `(lambda ...)` 前不用加 `#'`.
你要是为了可读性加的 `#'` 那当我没说.

**Comment by nasyxx** [comment]
> 你好多 `*-hook` 前都加了 `#'`, 真的没问题吗?
> 

你确定吗？

**Comment by shynur** [comment]
> 你确定吗？

随便举个例子: <https://github.com/nasyxx/emacs.d/blob/master/init-dont-panic.el#L6508>

**Comment by nasyxx** [comment]
> > 你确定吗？
> 
> 
> 
> 随便举个例子: <https://github.com/nasyxx/emacs.d/blob/master/init-dont-panic.el#L6508>

这是dont panic.  严格来说，这个文件只是改爆了配置后临时用一下的（你可以看见上一次更新都好几年前了）

**Comment by shynur** [comment]
哦, 看了下你的 `Makefile`, 大概知道你的 .emacs 是怎么构建的了.



> 这个文件只是改爆了配置后临时用一下的

除了这个文件, 其它地方也有不少 `#'*-hook` 的写法.

**Comment by nasyxx** [comment]
> 除了这个文件, 其它地方也有不少 `#'*-hook` 的写法.

你确定？

<img width="344" alt="Screenshot 2023-07-23 at 10 18 56 AM" src="https://github.com/nasyxx/emacs.d/assets/5007613/d97fe23f-b17a-464e-b540-9e0a459cbb4c">

**Comment by shynur** [comment]
> 除了这个文件, 其它地方也有不少 `#'*-hook` 的写法.

我没构建你的配置, 只是在目录下除了 `init-dont-panic.el` 的文件中用 `#'[^[:blank:]]+-hook[^[:alpha:]]` `project-search` 了一下.

**Comment by nasyxx** [comment]
> 另外看一下 `lambda` 宏的定义, `(lambda ...)` 展开之后就是 `#'(lambda ...)`, 所以 `(lambda ...)` 前不用加 `#'`. 你要是为了可读性加的 `#'` 那当我没说.

这个很早以前就讨论过了，避免出现不必要的`'(lambda ...)`这种放在list里面的时候。因为早期配置还用着动态作用域，有些地方是`'(lambda ...)`，也没有use-package之类的，很多东西都是list传来传去。这也和前面`#'-hook`有关，整个配置做过几次sed替换。

**Comment by nasyxx** [comment]
> 我没构建你的配置, 只是在目录下除了 `init-dont-panic.el` 的文件中用 `#'[^[:blank:]]+-hook[^[:alpha:]]` `project-search` 了一下.

那你可能搜索到了很多legacy内容，比如成dont panic的旧书。以及有一些虽然叫做`-hook`但实际上并不是hook而是callable的内容。

**Comment by shynur** [comment]
> 那你可能搜索到了很多legacy内容，比如成dont panic的旧书。

那没事了.

> 以及有一些虽然叫做`-hook`但实际上并不是hook而是callable的内容。

这个我有留意.
