### ISSUE TITLE
can't make

### ISSUE THREAD

**Issue by nmrvtz-zz** [nasyxx/emacs.d#3]
`make generate` returns
```
Generate init.el from README.org and literate-config.org.
Symbol's function definition is void: org-babel-tangle
make: *** [generate] Error 255
```
p.s. what's the theme on the screenshots?

**Comment by nasyxx** [comment]
Hi, `org-babel-tangle` is a built-in function in org-mode.  I guess you may check the version of your org-mode.

And the theme is doom-dracula (or other [doom-theme](https://github.com/hlissner/emacs-doom-themes), I am not really sure.)

**Comment by nmrvtz-zz** [comment]
Do I need any pre-installed emacs packages? p.s. theme on the screenshots is definitely not dracula

**Comment by nasyxx** [comment]
No.  What's your emacs version?

The theme is doom-vibrant

**Comment by nmrvtz-zz** [comment]
27.
![screenshot](https://github.com/nasyxx/emacs.d/raw/master/screenshot2.png)
This does not look like doom-vibrant ^

**Comment by nasyxx** [comment]
It does. 

<img width="1352" alt="Screen Shot 2019-09-27 at 10 33 39 PM" src="https://user-images.githubusercontent.com/5007613/65810309-e5d76580-e176-11e9-950e-b2e3afe0ee96.png">

The reason for the difference between them is the transparent, and violet shadows under the screenshot.
