### ISSUE TITLE
[Question] Why does the exclude argument of org-babel-tangle-publish ignore all files?

### ISSUE THREAD

**Issue by brsvh** [nasyxx/emacs.d#4]
Recently I've been read your configuration. I noticed that if I don't specify a specific file in `:include` field, the `:exclude ".*" ` will ignore all files. But it looks like should be ignoring hidden files that start with a period. And I didn't find the instruction in the `org` manual, so I want to know how it works.

https://github.com/nasyxx/emacs.d/blob/b0abf56823ab741c264a7136b9ff42ca1d9b7025/export.el#L39-L40

**Comment by nasyxx** [comment]
Hi,

Simply, the `".*"` not means `".*"` as it in the shell. It's a regex.  The dot means match any char.

From `org-publish-project-alist` docstring:

>The `:exclude` property may be used to prevent certain files from
being published.  Its value may be a string or regexp matching
file names you don't want to be published.
>The `:include` property may be used to include extra files.  Its
value may be a list of filenames to include.  The filenames are
considered relative to the base directory.
>When both `:include` and `:exclude` properties are given values,
the exclusion step happens first.

**Comment by brsvh** [comment]
I get it, thx u so much :+1:
