### ISSUE TITLE
Symbol’s value as variable is void: ibuffer

### ISSUE THREAD

**Issue by PsiACE** [nasyxx/emacs.d#5]
**Description :octocat:**

Warning (leaf): Error in 'nasy-editor-ibuffer' block at '~/.emacs.d/straight/build/nasy-tools/nasy-tools.el'.  Error msg: Symbol’s value as variable is void: ibuffer

**System Info :computer:**

    OS: Fedora33
    Emacs: 27.1
    Graphic display: t

**Comment by nasyxx** [comment]
Hi,

Sorry for the late reply. I have not found a good solution to this problem.  It only appears when you open Emacs for the first time after updating the configuration files.  

I suggest just ignore it now.

**Comment by PsiACE** [comment]
Ok, thannks
