### ISSUE TITLE
nasy-theme

### ISSUE THREAD

**Issue by terryzhouke** [nasyxx/emacs.d#7]
Warning (leaf): Error in `nasy-theme' block at `/Users/carol/.emacs.d/桃夭/庭尞/庭尞.el'.  Error msg\
: No ‘:repo’ specified for package ‘nasy-theme’

unable to find theme file nasy

**Comment by terryzhouke** [comment]
手动 git 解决问题，不知道为啥没有自动抓取
git clone https://github.com/nasyxx/emacs-nasy-theme.git ~/.emacs.d/木瓜/nasy/nasy-theme

**Comment by nasyxx** [comment]
> 手动 git 解决问题，不知道为啥没有自动抓取
> 
> git clone https://github.com/nasyxx/emacs-nasy-theme.git ~/.emacs.d/木瓜/nasy/nasy-theme
> 
> 

我的错，一直没修改 readme。需要

git clone --recursive

已经clone好的话，需要

git submodule update --init --recursive
