### ISSUE TITLE
Error in pre-command-hook

### ISSUE THREAD

**Issue by terryzhouke** [nasyxx/emacs.d#8]
Error in pre-command-hook (nasy-once-hook--nasy-first-key-hook-on-pre-command-hook): (user-error "consult--source-file is neither a Consult command nor a Consult source")
启动的时候有上述报错，不知道什么原因。另外 使用org-roam时无法用绑定的快捷键
File mode specification error: (void-function define-keymap)
nasy/-keymap: Symbol’s function definition is void: define-keymap

**Comment by nasyxx** [comment]
> Error in pre-command-hook (nasy-once-hook--nasy-first-key-hook-on-pre-command-hook): (user-error "consult--source-file is neither a Consult command nor a Consult source")

这个错误是因为 consult 前不久更新了，最近挺忙的，一直没来得及改。

> File mode specification error: (void-function define-keymap)
nasy/-keymap: Symbol’s function definition is void: define-keymap

这个是需要 emacs 29，就是从 git master branch 编译

**Comment by nasyxx** [comment]
等过两天我 push 下本地修改

**Comment by nasyxx** [comment]
好了，更新好了（
