### ISSUE TITLE
parinfer-rust-darwin.so cannot support apple silicon m1 

### ISSUE THREAD

**Issue by terryzhouke** [nasyxx/emacs.d#9]
byte-code: Module could not be opened: "/Users/zhouke/.emacs.d/萚兮/旹/parinfer-rust/parinfer-rust-darwin.so", "dlopen(/Users/zhouke/.emacs.d/萚兮/旹/parinfer-rust/parinfer-rust-darwin.so, 0x0009): tried: '/Users/zhouke/.emacs.d/萚兮/旹/parinfer-rust/parinfer-rust-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/parinfer-rust-darwin.so' (no such file), '/usr/lib/parinfer-rust-darwin.so' (no such file), '/Users/zhouke/.emacs.d.nasy/萚兮/旹/parinfer-rust/parinfer-rust-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/parinfer-rust-darwin.so' (no such file), '/usr/lib/parinfer-rust-darwin.so' (no such file)"

这个文件不支持 m1 的芯片，是否可以本地编译进行替代。我编译出来的文件是 dylib文件 怎么导入到配置中？

**Comment by nasyxx** [comment]
参考 https://github.com/justinbarclay/parinfer-rust-mode

直接 `mv /path/to/dylib 萚兮/旹/parinfer-rust/parinfer-rust-darwin.so` 就行了

**Comment by terryzhouke** [comment]
byte-code: Module is not GPL compatible: "/Users/carol/.emacs.d/萚兮/旹/parinfer-rust/parinfer-rust-darwin.so

**Comment by nasyxx** [comment]
> justinbarclay/parinfer-rust-mode

`cargo build --release --features emacs`

**Comment by terryzhouke** [comment]
谢谢，解决了
